spring.application.name=auth-service

server.port=9090

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/auth_core
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgresql}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kartikkamatkar98@gmail.com
spring.mail.password=${MAIL_PASSWORD:krthbyifxuparwlo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

# JWT Secret
jwt.secret=${JWT_SECRET:QuizLYSecretKeyForJwtTokenGeneration2026}

# Actuator & Observability
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always