spring.application.name=api-gateway
server.port=6063

spring.cloud.gateway.routes[0].id=quiz-service
spring.cloud.gateway.routes[0].uri=http://localhost:6060
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/questions/**

spring.cloud.gateway.routes[1].id=attempt-service
spring.cloud.gateway.routes[1].uri=http://localhost:6061
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/attempts/**

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**