spring.application.name=attempt-service

server.port=6061

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/attempts
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgresql}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

# OpenFeign Client
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# Actuator & Observability
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always