input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json
  }
}

filter {
  # Add filters / parsing rules here if needed
  mutate {
    add_field => { "application" => "%{[spring][application][name]}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "quizly-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
