spring.application.name=quiz-service
spring.config.import=optional:configserver:http://localhost:8888

# Offline Fallback / Mock settings (Chat model is real, Vector DB is mocked)
ai.mock.chat=false
ai.mock.vectorstore=true
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.vectorstore.qdrant.QdrantVectorStoreAutoConfiguration

spring.ai.openai.api-key=6d6a62665c5c4c4fb382b9115c08ea38.ILZUtBFi8lebu-V1cOZWIxVx
spring.ai.openai.base-url=https://open.bigmodel.cn/api/paas/v4
spring.ai.openai.chat.options.model=glm-4